name: Deploy to GH Pages

on: 
  push:
    branches:
      - "master"

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update theme
        run: git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: "0.101.0"

      - name: Build Site
        run: hugo --minify

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          branch: rendered
          folder: ./public